name: PR Information and API Call

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
  ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}


jobs:
  collect-info-and-call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Git Repo Details
        id: extract_info
        run: |
          REPO_NAME=$(basename ${GITHUB_REPOSITORY})
          REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          echo "REPOSITORY_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "TARGET_BRANCH_NAME=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          echo "REPOSITORY_URL=${REPO_URL}" >> $GITHUB_ENV
          echo "PULL_REQUEST_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Get OAuth token
        id: get_token
        run: |
          CLIENT_ID="${ANYPOINT_CLIENT_ID}"
          CLIENT_SECRET="${ANYPOINT_CLIENT_SECRET}"
          
          # Make a request to your token service to obtain a token
          # Replace 'https://example.com/token' with your actual token service endpoint
          TOKEN=$(curl -X POST -u "${CLIENT_ID}:${CLIENT_SECRET}" -d "grant_type=client_credentials" https://example.com/token)
          echo "TOKEN=$(echo $TOKEN | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Call API
        id: call_api
        env:
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}
          TARGET_BRANCH_NAME: ${{ env.TARGET_BRANCH_NAME }}
          REPOSITORY_URL: ${{ env.REPOSITORY_URL }}
          PULL_REQUEST_NUMBER: ${{ env.PULL_REQUEST_NUMBER }}
          TOKEN: ${{ env.TOKEN }}
        run: |
          # Construct JSON payload
          JSON_PAYLOAD="{\"domainName\":\"${REPOSITORY_NAME}\",\"domainGitRepo\":\"${REPOSITORY_URL}\",\"domainTargetGitBranch\":\"${TARGET_BRANCH_NAME}\",\"prNumber\":\"${PULL_REQUEST_NUMBER}\"}"
          
          # Assuming your API endpoint is https://example.com/api
          # Replace 'Bearer <token>' with your actual token
          API_RESPONSE=$(curl -s -X POST -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" -d "${JSON_PAYLOAD}" https://example.com/api)
          echo "::set-output name=status::$(echo $API_RESPONSE | jq -r '.status')"
          echo "::set-output name=trace_id::$(echo $API_RESPONSE | jq -r '.traceId')"
          if [ "$(echo $API_RESPONSE | jq -r '.status')" == "ERROR" ]; then
            echo "::error::API call failed with errors: $(echo $API_RESPONSE | jq -r '.errors | join(", ")')"
            exit 1
          fi
